export const JobList: Job[] = [
     {
    id: 22,
    heading: "CXQO Associate | Amazon | Hyderabad",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/dirc1/apply/?event=14050&job=58038",
    image_url: "/static/img/hp.png",
  },
     {
    id: 21,
    heading: "Domain Trainee | Genpact | Jaipur",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=INS023413",
    image_url: "/static/img/hp.png",
  },
     {
    id: 20,
    heading: "QA Engineer | ZOHO Corp | Chennai",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614913581",
    image_url: "/static/img/hp.png",
  },
    {
    id: 19,
    heading: "Consultant Internship | Deloitte | Bangalore",
    link: "https://jobsindia.deloitte.com/job/Bengaluru-Consulting-Internship/23914944/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 18,
    heading: "Software Development Engineer | Urban Company | Gurgaon",
    link: "https://careers.urbancompany.com/jobDetail?id=eb369381-1cfe-432f-affc-12070d83a2c6",
    image_url: "/static/img/hp.png",
  },
    {
    id: 17,
    heading: "Analyst | EY | Noida",
    link: "https://careers.ey.com/ey/job/Noida-Analyst-Forensics-National-ASU-Forensics-Investigations-&-Compliance-Noida-UP-201304/1003553001/",
    image_url: "/static/img/hp.png",
  },
   {
    id: 16,
    heading: "Quality Analyst | Revolut | Work From Home",
    link: "https://www.revolut.com/en-IN/careers/position/quality-assurance-analyst-0f7bfdfb-6fd1-4fbe-b586-f62f84536fa9/",
    image_url: "/static/img/hp.png",
  },
   {
    id: 15,
    heading: "Software Engineer Intern | NIKE | Bangalore",
    link: "https://jobs.nike.com/job/R-24752?cp=76060516106_aff_je6NUbpObpQ&ranMID=41134&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-UmBg0FI_AoHwGdLO5ac13w",
    image_url: "/static/img/hp.png",
  },
   {
    id: 14,
    heading: "iOS Developer | Meesho | Bangalore",
    link: "https://jobs.lever.co/meesho/6e0e5074-e1bb-41c6-89bb-2c20d36d4b0f/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 13,
    heading: "Software Engineer | Microsoft | Bangalore / WFH",
    link: "https://jobs.careers.microsoft.com/global/en/job/1704435/Software-Engineer",
    image_url: "/static/img/hp.png",
  },
  {
    id: 12,
    heading: "Quality Associate | Amazon | Hyderabad",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=58218&e=14250",
    image_url: "/static/img/hp.png",
  },
  {
    id: 11,
    heading: "Associate Consultant | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10015744",
    image_url: "/static/img/hp.png",
  },
  {
    id: 10,
    heading: "Associate Software Engineer | Oracle | Bangalore",
    link: "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/233846",
    image_url: "/static/img/hp.png",
  },
  {
    id: 9,
    heading: "Software Development Engineer | Adobe | Noida",
    link: "https://careers.adobe.com/us/en/job/ADOBUSR145089EXTERNALENUS/Software-Development-Engineer",
    image_url: "/static/img/hp.png",
  },
  {
    id: 8,
    heading: "Developer Associate | SAP | Bangalore",
    link: "https://jobs.sap.com/job/Bangalore-Developer-Associate-KA-560066/1055158601/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 7,
    heading: "Software Developer | ZOHO | Pan India",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614929615",
    image_url: "/static/img/hp.png",
  },
  {
    id: 6,
    heading: "Software Engineer | Myntra | Bangalore",
    link: "https://boards.greenhouse.io/myntra/jobs/7216939002?",
    image_url: "/static/img/hp.png",
  },
  {
    id: 5,
    heading: "Process Analyst | IBM | Bangalore",
    link: "https://www.naukri.com/job-listings-process-analyst-recruitment-ibm-india-pvt-limited-bengaluru-0-to-3-years-260324910641?src=jobsearchDesk&sid=17115543450314158&xp=10&px=1&nignbevent_src=jobsearchDeskGNB",
    image_url: "/static/img/hp.png",
  },
  {
    id: 4,
    heading: "System Analyst | Nielsen | Bangalore",
    link: "https://jobs.lever.co/nielsen/fed9aa65-af08-42b3-b740-441e4da27f02",
    image_url: "/static/img/hp.png",
  },
  {
    id: 3,
    heading: "Development Associate | Accenture | Pan India",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/25377/job-details",
    image_url: "/static/img/jnj.png",
  },
  {
    id: 2,
    heading: "Technology Analyst | Deloitte | Hyderabad/Pune",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-EH24-TAX-GESTC-B2B-Helpdesk-BTA-Hyd-Pun/140758",
    image_url: "/static/img/infor.png",
  },
  {
    id: 1,
    heading: "Data Analyst | Walmart | Bangalore",
    link: "https://walmart.wd5.myworkdayjobs.com/en-US/WalmartExternal/job/DATA-ANALYST-II--DATA-ANALYTICS_R-1796887-1",
    image_url: "/static/img/Deloitte_Logo.png",
  },
];
