export const JobList: Job[] = [
  {
    id: 292,
    heading: "Software Developer | IBM | Bangalore",
    link: "https://careers.ibm.com/job/21335919/software-developer-bangalore-in/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 291,
    heading: "Sofware Engineer | Optum | Hyderabad - Noida,
    link: "https://careers.unitedhealthgroup.com/job/21243748/software-engineer-hyderabad-in/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 290,
    heading: "Junior Data Analyat | Cognizant | Multiple Location",
    link: "https://careers.cognizant.com/india-en/jobs/00060972161/junior-data-analyst/",
    image_url: "/static/img/hp.png",
  },
 {
    id: 289,
    heading: "Data Analyst | TIAA | Work From Home",
    link: "https://tinyurl.com/tiaa-freshers",
    image_url: "/static/img/hp.png",
  },
     {
    id: 288,
    heading: "Intern | NTT DATA | Bangalore",
    link: "https://careers.services.global.ntt/global/en/job/R-121946/Intern",
    image_url: "/static/img/hp.png",
  },
    {
    id: 287,
    heading: "Associate Engineer | Qualcomm | Hyderabad",
    link: "https://cuvette.tech/app/other-jobs/6745db1922860e72c5bbf796?referralCode=1P05IC",
    image_url: "/static/img/hp.png",
  },
{
    id: 286,
    heading: "Associate | Accenture | Bangalore",
    link: "https://www.accenture.com/in-en/careers/jobdetails?src=LINKEDINJP&id=AIOC-S01554162_en",
    image_url: "/static/img/hp.png",
  },
    {
    id: 285,
    heading: "Developer | SAP | Bangalore",
    link: "https://jobs.sap.com/job/Bangalore-Developer-ABAP-S4HANA-Procurement-560066/1090451901/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 284,
    heading: "Business Analyst | Amazon | Hyderabad",
    link: "https://www.amazon.jobs/en/jobs/2696682/business-analyst-i-roc-analytics-roc",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 283,
    heading: " SDE Intern | Ridecell | Pune",
    link: "https://docs.google.com/forms/d/e/1FAIpQLScT2gdgW-LQMThkFGlhi6LI3lmJp127-TaSus1rWwpdI_g7sQ/viewform",
    image_url: "/static/img/hp.png",
  },
    {
    id: 282,
    heading: "Trainee | Monotype | Noida",
    link: "https://monotype.wd1.myworkdayjobs.com/en-US/Monotype/job/Noida/Trainee--Market-Intelligence_R0003664",
    image_url: "/static/img/hp.png",
  },
    {
    id: 281,
    heading: "Apprentice | S&P global | Gurgaon & Hyderabad",
    link: "https://careers.spglobal.com/jobs/305935?lang=en-us",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 280,
    heading: "Software Engineer | Clarivate | Work From Home",
    link: "https://careers.clarivate.com/job/CLACLAGBJREQ128166EXTERNALENGB/Software-Engineer-Java",
    image_url: "/static/img/hp.png",
  },
    {
    id: 279,
    heading: "Trainee | Siemens | Pune",
    link: "https://jobs.siemens.com/careers/job/563156120234562",
    image_url: "/static/img/hp.png",
  },
    {
    id: 278,
    heading: "Python Developer | Panasonic | Bangalore",
    link: "https://careers.na.panasonic.com/jobs/10425",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 277,
    heading: "Intern | Microchip | Chennai",
    link: "https://wd5.myworkdaysite.com/en-US/recruiting/microchiphr/External/job/India---Chennai/Intern_R938-24",
    image_url: "/static/img/hp.png",
  },
    {
    id: 276,
    heading: "SDE Intern | The Lean Product Studio | Pune",
    link: "https://unstop.com/internships/software-development-internship-flutter-the-lean-product-studio-1111173?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
    {
    id: 275,
    heading: "Razorpay Intern | Razorpay | Bangalore",
    link: "https://job-boards.greenhouse.io/razorpaysoftwareprivatelimited/jobs/4439466005",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 274,
    heading: "Support Engineer | PowerSchool | Bengaluru",
    link: "https://careers3-powerschool.icims.com/jobs/6980/job?mobile=false&width=1170&height=500&bga=true&needsRedirect=false&jan1offset=330&jun1offset=330",
    image_url: "/static/img/hp.png",
  },
    {
    id: 273,
    heading: "Junior QA Tester | Kwalee | Bengaluru",
    link: "https://jobs.eu.lever.co/kwalee/c59afc2f-8160-4ed8-a33e-bbc6d48ef521/apply?lever-source%5B%5D=LinkedIn&lever-origin=applied",
    image_url: "/static/img/hp.png",
  },
    {
    id: 272,
    heading: "Associate | Genpact | Bangalore",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?src=DS-10971&job=1396240",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 271,
    heading: "Software Engineer | Greenway | Work From Home",
    link: "https://recruit.hirebridge.com/v3/careercenter/v2/details.aspx?jid=597662&cid=6709&locvalue=1174",
    image_url: "/static/img/hp.png",
  },
    {
    id: 270,
    heading: "Software Engineer | Akamai | Work From Home",
    link: "https://akamaicareers.inflightcloud.com/jobdetails/aka_ext/035360?section=aka_ext&job=035360",
    image_url: "/static/img/hp.png",
  },
    {
    id: 269,
    heading: "Associate Engineer | NTT Data | New Delhi",
    link: "https://careers.services.global.ntt/global/en/job/R-116799/apply",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 268,
    heading: "Engineer Intern | Oceaneering | Pune",
    link: "https://careers.oceaneering.com/global/en/job/OCINGLOBAL8229",
    image_url: "/static/img/hp.png",
  },
    {
    id: 267,
    heading: "Product Intern | Standard Chartered | Bangalore",
    link: "https://jobs.standardchartered.com/job/Bangalore-2025-Product-Control-Intern-GBS-India/800352302/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 266,
    heading: "IT Intern | Paytm | Noida",
    link: "https://jobs.lever.co/paytm/1e580ff2-56b8-43de-aeb7-f5907945daaf",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 265,
    heading: "ITPT OFFCAMPUS | Cognizant | Pan India",
    link: "https://app.joinsuperset.com/join/#/signup/student/jobprofiles/92217fe2-2130-461c-9be3-97c0ffb9e9da",
    image_url: "/static/img/hp.png",
  },
    {
    id: 264,
    heading: "QA Engineer | Cencora | Pune",
    link: "https://myhrabc.wd5.myworkdayjobs.com/en-US/Global/job/Pune-India/Engineer---Quality---Testing_R2416313",
    image_url: "/static/img/hp.png",
  },
    {
    id: 263,
    heading: "System Associate | Accenture | Pan India",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/129361/job-details",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 262,
    heading: "Data Analyst | Vodafone | Pune",
    link: "https://opportunities.vodafone.com/job/Pune-Data-Analyst-Jedox/1101464501/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 261,
    heading: "Java Developer | NTTData | Bangalore",
    link: "https://nttdata.eightfold.ai/careers?seniority=Entry&pid=563327918838303&domain=nttdata.com&sort_by=relevance",
    image_url: "/static/img/hp.png",
  },
    {
    id: 260,
    heading: "Data Analyst | Wipro | Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3091046",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 259,
    heading: "BDE Intern | Paytm | Mumbai",
    link: "https://jobs.lever.co/paytm/3ac2c184-755a-4e9d-9e9a-92f649415dc6?utm_source=Business_Development_Consultant_Internship_unstop&utm_medium=listing&utm_campaign=unstop",
    image_url: "/static/img/hp.png",
  },
    {
    id: 258,
    heading: "Data Science Intern | Pfizer | Mumbai, Chennai",
    link: "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers/job/India---Chennai/Data-Science-Intern_4916949?source=linkedin",
    image_url: "/static/img/hp.png",
  },
    {
    id: 257,
    heading: "Software Engineer Intern | Microsoft | Pan India",
    link: "https://jobs.careers.microsoft.com/global/en/job/1743242/Software-Engineering%3A-Internship-Opportunity",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 256,
    heading: "Analyst | eClerx | Pune",
    link: "https://fa-ewji-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/75485",
    image_url: "/static/img/hp.png",
  },
    {
    id: 255,
    heading: "Data Analyst | UST | Bangalore",
    link: "https://usource.ripplehire.com/candidate/?token=8YxWjpwDhdL62DFYUIcQ&lang=en&source=USTLINKEDIN&ref=USTLINKEDIN#detail/job/22616",
    image_url: "/static/img/hp.png",
  },
    {
    id: 254,
    heading: "Business Analyst | Capgemini | Pune",
    link: "https://www.capgemini.com/in-en/jobs/4b1lxZABje7kHFfZvW32/v-business-analyst--mumbai/",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 253,
    heading: "Data Analyst | Emerson | Pune",
    link: "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/23013268",
    image_url: "/static/img/hp.png",
  },
    {
    id: 252,
    heading: "Software Developer | Siemens | Bengaluru",
    link: "https://jobs.siemens.com/careers?query=%2A&location=india&pid=563156120171032&domain=siemens.com&sort_by=relevance&microsite=siemens.com",
    image_url: "/static/img/hp.png",
  },
    {
    id: 251,
    heading: "Software Engineer | Genpact | Bangalore",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?src=DS-10971&job=1393819",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 250,
    heading: "Engineering Intern | Myntra | Bengaluru",
    link: "https://cuvette.tech/app/dashboard/other-jobs/66699b7a689b726b76593b4f",
    image_url: "/static/img/hp.png",
  },
    {
    id: 249,
    heading: "Data Analytics Intern | Tata Cliq | Mumbai",
    link: "https://cuvette.tech/app/dashboard/other-jobs/666e99b3b03a438ea62c2b17",
    image_url: "/static/img/hp.png",
  },
    {
    id: 248,
    heading: "Summer Intern | Baker Hughes | Mumbai ",
    link: "https://cuvette.tech/app/dashboard/other-jobs/66a4d3ab82faaa87cb97dcb4",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 247,
    heading: "Talent Acquisition Intern | Unstop | Delhi",
    link: "https://unstop.com/internships/talent-acquisition-intern-unstop-982457?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
    {
    id: 246,
    heading: "Business Intern | Myntra | Bengaluru",
    link: "https://unstop.com/internships/intern-business-finance-myntra-1071988?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
    {
    id: 245,
    heading: "Graduate Trainee | Jio | Mumbai ",
    link: "https://careers.jio.com/frmjobdescription.aspx?JBTITLE=vxpFHGTbi%2fwqGqTPHnXtsA%3d%3d&jbID=IosACTfrHnilV3Z3WUgnNA%3d%3d&funcCode=tBOU2f2ubJIKJJaEorlljoC0jBhJb9cLpWXiiP5HyBU%3d",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 244,
    heading: "Test Engineer | Yash | Bangalore",
    link: "https://careers.yash.com/job/Bangalore-Jr_-Software-Tester-Job-KA/1054104266/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 243,
    heading: "Software Engineer | Tech Mahindra | Pune",
    link: "https://cuvette.tech/app/dashboard/other-jobs/66a3315567849e8dc17ef5c7",
    image_url: "/static/img/hp.png",
  },
    {
    id: 242,
    heading: "Consulting | EY | Pune",
    link: "https://eyglobal.yello.co/jobs/zBGCeHRCAUJcW1nztz1qzQ?job_board_id=c1riT--B2O-KySgYWsZO1Q",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 241,
    heading: "Analyst | eClerx | Pune",
    link: "https://fa-ewji-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/75462",
    image_url: "/static/img/hp.png",
  },
    {
    id: 240,
    heading: "Product Analyst Intern | BCG | New Delhi",
    link: "https://careers.bcg.com/job/23731BR/Product-Analyst-Intern",
    image_url: "/static/img/hp.png",
  },
    {
    id: 239,
    heading: "SDE Intern | HP | Bengaluru",
    link: "https://cuvette.tech/app/dashboard/other-jobs/66a29e36c432b921f3da911e",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 238,
    heading: "Data Analyst | Emerson | Pune",
    link: "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/23013268",
    image_url: "/static/img/hp.png",
  },
    {
    id: 237,
    heading: "Software Testing Intern | Sequentia | Pune",
    link: "https://www.sequentia.in/Software-Tester-Intern",
    image_url: "/static/img/hp.png",
  },
    {
    id: 236,
    heading: "Technical Associate | Genpact | Hyderabad",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?src=DS-10971&job=1390819",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 235,
    heading: "Web Developer | Zoho | Work From Home",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614913786",
    image_url: "/static/img/hp.png",
  },
    {
    id: 234,
    heading: "Software Engineer | Principal | Pune",
    link: "https://careers.principal.com/in/jobs/43201/job",
    image_url: "/static/img/hp.png",
  },
    {
    id: 233,
    heading: "Data Analyst | Cognizant | Mumbai",
    link: "https://careers.cognizant.com/global-en/jobs/00059444541/junior-data-analyst/?src=SNS-102?JB-11500",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 232,
    heading: "Cyber Security Intern | Airbus | Bangalore",
    link: "https://unstop.com/internships/cyber-security-intern-airbus-1072104?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
    {
    id: 231,
    heading: "Talent Acquisition Intern | Infrrd | Bangalore",
    link: "https://infrrd.bamboohr.com/careers/132",
    image_url: "/static/img/hp.png",
  },
    {
    id: 230,
    heading: "Software Engineer Intern | Kaplan | Bangalore",
    link: "https://ghc.wd1.myworkdayjobs.com/en-US/Kaplan_Careers/job/Bangalore-KA-India/Associate-Software-Engineer--Hybrid-_JR240442-1",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 229,
    heading: "Software Engineer | Zebra | Pune",
    link: "https://careers.zebra.com/careers/job/343619312416?domain=zebra.com",
    image_url: "/static/img/hp.png",
  },
    {
    id: 228,
    heading: "Graduate Trainee | Siemens | Bengaluru",
    link: "https://jobs.siemens.com/careers/job/563156120088350?hl=en&domain=siemens.com&sourceType=PREMIUM_POST_SITE",
    image_url: "/static/img/hp.png",
  },
    {
    id: 227,
    heading: "Process Associate | IBM | Gurgaon",
    link: "https://careers.ibm.com/job/20731479/process-associate-finance-and-administration-delivery-gurgaon-in/",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 226,
    heading: "Intern | Salesforce | Bangalore,Hyderabad",
    link: "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site/job/India---Hyderabad/Intern_JR250704?source=LinkedIn_Jobs",
    image_url: "/static/img/hp.png",
  },
    {
    id: 225,
    heading: "Engineering Intern | Microsoft | Across India",
    link: "https://jobs.careers.microsoft.com/global/en/job/1743242/Software-Engineering%3A-Internship-Opportunity",
    image_url: "/static/img/hp.png",
  },
    {
    id: 224,
    heading: "Engineer Intern | Google | Across India",
    link: "https://www.google.com/about/careers/applications/jobs/results/83484176157680326-software-engineering-intern-summer-2025",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 223,
    heading: "Data Enginner | Magna | Bangalore",
    link: "https://jobs.magna.com/job/Bangalore-Date-Engineer/582228917/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 222,
    heading: "Data Enginner | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10019786",
    image_url: "/static/img/hp.png",
  },
    {
    id: 221,
    heading: "Development Associate | Accenture | Across India",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/25377/job-details",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 220,
    heading: "Business Intern | Keka | Mumbai",
    link: "https://ketto.keka.com/careers/jobdetails/64125",
    image_url: "/static/img/hp.png",
  },
    {
    id: 219,
    heading: "Intern | Danaher | Bangalore",
    link: "https://jobs.danaher.com/global/en/job/DANAGLOBALR1269605EXTERNALENGLOBAL/Intern",
    image_url: "/static/img/hp.png",
  },
    {
    id: 218,
    heading: "PMA Intern | Luxoft | Work From Home",
    link: "https://career.luxoft.com/jobs/pma-intern-6702",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 217,
    heading: "Software Engineering | WesternDigital | Bengaluru",
    link: "https://jobs.smartrecruiters.com/WesternDigital/744000001182425-engineer-software-engineering-ncg-hiring-be-2024-c-or-c-",
    image_url: "/static/img/hp.png",
  },
    {
    id: 216,
    heading: "Quality Analyst | Infor | Bengaluru",
    link: "https://careers.infor.com/en_US/careers/JobDetail/Quality-Assurance-Analyst-Associate/14544#",
    image_url: "/static/img/hp.png",
  },
    {
    id: 215,
    heading: "Quality Analyst | DE Shaw&Co | Hyderabad",
    link: "https://www.deshawindia.com/careers/associate-qae-qte-fte-off-campus-2024-grads-5482",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 214,
    heading: "Graduate Intern | Mr Cooper | Chennai",
    link: "https://nationstar.wd5.myworkdayjobs.com/en-US/MrCooper/job/Chennai-NSM-Block-7/Graduate-Intern_022555",
    image_url: "/static/img/hp.png",
  },
    {
    id: 213,
    heading: "Data Science Intern | Antino  | Gurugram",
    link: "https://antino.freshteam.com/jobs/RgDxWyxePE3H/data-science-intern",
    image_url: "/static/img/hp.png",
  },
    {
    id: 212,
    heading: "Data Analyst Intern | S&P Global | Bangalore",
    link: "https://careers.spglobal.com/jobs/304891?lang=en-us",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 211,
    heading: "Application Support | Deloitte | Delhi",
    link: "https://jobsindia.deloitte.com/job/Delhi-Enabling-Areas-Application-Support-Qualtrics-Information-Technology/20244744/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 210,
    heading: "Software Engineer | PayPal | Chennai",
    link: "https://paypal.eightfold.ai/careers/job/274901903829",
    image_url: "/static/img/hp.png",
  },
    {
    id: 209,
    heading: "Devops Engineer | Intel | Bengaluru",
    link: "https://jobs.intel.com/en/job/bengaluru/infrastructure-and-devops-engineer/41147/67033779792",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 208,
    heading: "Executives | EXL | Pune",
    link: "https://exlcareers.peoplestrong.com/job/detail/EXL_E_1087365",
    image_url: "/static/img/hp.png",
  },
    {
    id: 207,
    heading: "Tech Intern Trainee | UBS | India",
    link: "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad?jobid=304889&siteid=5012&partnerid=25008&PageType=JobDetails#jobDetails=304889_5012",
    image_url: "/static/img/hp.png",
  },
    {
    id: 206,
    heading: "QA Intern | PitneyBowes | Pune",
    link: "https://careers.pitneybowes.com/global/en/job/PIBOGLOBALR18422EXTERNALENGLOBAL/Intern-QA",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 205,
    heading: "Trainee Engineer | NTT DATA | Bangalore",
    link: "https://careers.services.global.ntt/global/en/job/R-116691/apply?utm_medium=phenom-feeds&utm_source=linkedin",
    image_url: "/static/img/hp.png",
  },
    {
    id: 204,
    heading: "Management Trainee | Genpact | Mumbai",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=BFS037677",
    image_url: "/static/img/hp.png",
  },
    {
    id: 203,
    heading: "Data Analyst | Wipro | Gurugram",
    link: "https://careers.wipro.com/careers-home/jobs/3076738",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 202,
    heading: "Tech Intern | Medtronic | India",
    link: "https://jobs.medtronic.com/careers/job/22420401",
    image_url: "/static/img/hp.png",
  },
    {
    id: 201,
    heading: "SDE Testing Intern | GKF | Pune",
    link: "https://gfk.wd3.myworkdayjobs.com/en-US/Corporate_Careers/job/NIQ-Pune/Junior-Software-Development-Engineer-in-Test_R00022924-2",
    image_url: "/static/img/hp.png",
  },
    {
    id: 200,
    heading: "Data Scientist Intern | ISB | Hyderabad",
    link: "https://www.isb.edu/en/careers/non-academic-openings/data-scientist---intern--ee.html",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 199,
    heading: "Associate Engineer | United | Gurugram",
    link: "https://careers.united.com/us/en/job/GGN00001545/Associate-Engineer-IT-Quality",
    image_url: "/static/img/hp.png",
  },
    {
    id: 198,
    heading: "Software Engineer | RedHat | Work From Home",
    link: "https://redhat.wd5.myworkdayjobs.com/jobs/job/Remote-India/Software-Engineer_R-039190?%2526iisn=LinkedIn%252BPosting&source=LinkedIn&%2526%253Fmode=job&%2526iis=Job%252BBoard",
    image_url: "/static/img/hp.png",
  },
    {
    id: 197,
    heading: "Operation Associate | Amazon | Hyderabad",
    link: "https://www.amazon.jobs/en/jobs/2693294/advocacy-operations-associate-advocacy-operations",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 196,
    heading: "SDET Intern | Trellix | Bangalore",
    link: "https://trellix.wd1.myworkdayjobs.com/EnterpriseCareers/job/India-Bangalore/Apprentice---SDET_JR0033554?source=LinkedIn",
    image_url: "/static/img/hp.png",
  },
    {
    id: 195,
    heading: "Engineering Intern | Aurva | Bengaluru",
    link: "https://wellfound.com/jobs/2892047-software-engineering-intern?autoOpenApplication=true",
    image_url: "/static/img/hp.png",
  },
    {
    id: 194,
    heading: "R&D Intern | Zoho | Kottarakkara",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1bc9a8b443ab578a0c2a130b45fdbb0a1",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 193,
    heading: "Process Associate | Genpact | Gurugram",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?src=DS-10971&job=1371343",
    image_url: "/static/img/hp.png",
  },
    {
    id: 192,
    heading: "Software Developer | Blinkit | Gurgaon",
    link: "https://www.instahyre.com/job-324705-software-development-engineer-i-at-blinkit-gurgaon/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 191,
    heading: "Programmer Analyst | Cognizant | Bangalore",
    link: "https://careers.cognizant.com/global-en/jobs/000578964712/programmer-analyst/?src=SNS-102?JB-11500",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 190,
    heading: "AI Intern | Sony | Work From Home",
    link: "https://www.linkedin.com/jobs/view/3947605417/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 189,
    heading: "Data Analyst Intern | Versor | Work From Home",
    link: "https://www.versorinvest.com/careers/data-analyst-intern-india/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 188,
    heading: "SDE Intern | Sharechat | Bangalore",
    link: "https://www.instahyre.com/job-309128-sde-intern-internship-at-sharechat-bangalore/",
    image_url: "/static/img/hp.png",
  }, 
    {
    id: 187,
    heading: "Azure Devops | Deloitte | Mumbai",
    link: "https://jobsindia.deloitte.com/job/Mumbai-Enabling-Areas-Azure-Devops-Information-Technology/23448944/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 186,
    heading: "Process Associate | Genpact | Hyderabad",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=HIG018171",
    image_url: "/static/img/hp.png",
  },
    {
    id: 185,
    heading: "Process Executive | Infosys | Chennai",
    link: "https://career.infosys.com/jobdesc?source=44003&jobReferenceCode=PROGEN-EXTERNAL-186307",
    image_url: "/static/img/hp.png",
  }, 
  {
    id: 184,
    heading: "DevOps Intern | Syfe | Gurugram",
    link: "https://careers.syfe.com/jobs/Cnv-bYtTdVwD/devops-intern",
    image_url: "/static/img/hp.png",
  },
    {
    id: 183,
    heading: "SEO Intern | SportsKeeda | Work From Home",
    link: "https://sportskeeda.zohorecruit.in/jobs/Careers/59509000024729021/SEO-Intern?source=CareerSite",
    image_url: "/static/img/hp.png",
  },
    {
    id: 182,
    heading: "Backend Intern | Syfe | Gurugram",
    link: "https://careers.syfe.com/jobs/jt6vmXoVmu-i/backend-intern",
    image_url: "/static/img/hp.png",
  }, 
  {
    id: 181,
    heading: "Data Analyst | Kone | Chennai",
    link: "https://kone.wd3.myworkdayjobs.com/Careers/job/Chennai-ITECKBS/Data-Analyst_R0639970/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 180,
    heading: "Technology Campus Hire | EY | Hyderabad",
    link: "https://eyglobal.yello.co/jobs/wf7FaxbvMhNsuMPx5Xfy0A?job_board_id=c1riT--B2O-KySgYWsZO1Q",
    image_url: "/static/img/hp.png",
  },
    {
    id: 179,
    heading: "Junior Data Analyst | Cognizant | Pune",
    link: "https://careers.cognizant.com/global-en/jobs/00059475331/trainee-junior-data-analyst/?src=SNS-102?JB-11500",
    image_url: "/static/img/hp.png",
  }, 
  {
    id: 178,
    heading: "Java Intern | Mobzway | Jaipur",
    link: "https://unstop.com/internships/java-internship-mobzway-1061264?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
    {
    id: 177,
    heading: "SDE Intern | Fyndjobs | Bengaluru",
    link: "https://www.linkedin.com/jobs/view/3968270385/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 176,
    heading: "Software Engineer Intern | HashiCorp | Bengaluru",
    link: "https://www.hashicorp.com/career/6050047?gh_src=a8bc2ad21",
    image_url: "/static/img/hp.png",
  }, 
  {
    id: 175,
    heading: "Process Associate | Mr Cooper | Bengaluru, Chennai",
    link: "https://careers.mrcooper.com/us/en/job/MRCOUS022504EXTERNALENUS/Process-Associate-Trainee",
    image_url: "/static/img/hp.png",
  },
    {
    id: 174,
    heading: "Data Analyst | JP Morgan | Bengaluru",
    link: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210366839",
    image_url: "/static/img/hp.png",
  },
    {
    id: 173,
    heading: "Analyst Trainee | Deloitte | Work From Home",
    link: "https://www.instahyre.com/job-309989-analyst-trainee-at-deloitte-work-from-home/",
    image_url: "/static/img/hp.png",
  }, 
  {
    id: 172,
    heading: "HR Intern | Airbus | Bangalore",
    link: "https://ag.wd3.myworkdayjobs.com/en-US/Airbus/job/Bangalore-Area/HR-INTERN_JR10271187",
    image_url: "/static/img/hp.png",
  },
    {
    id: 171,
    heading: "IT Intern | P&G | Mumbai",
    link: "https://www.pgcareers.com/global/en/job/R000110490/Internship---Information-Technology",
    image_url: "/static/img/hp.png",
  },
    {
    id: 170,
    heading: "Development Intern | Paytm | Work From Home",
    link: "https://www.naukri.com/job-listings-business-development-intern-paytm-remote-0-to-0-years-051223501206?src=cluster&sid=17200334795255189_1&xp=1&px=1",
    image_url: "/static/img/hp.png",
  }, 
  {
    id: 169,
    heading: "QA Engineer | Dyson | Bangalore",
    link: "https://dyson.wd3.myworkdayjobs.com/dyson_careers/job/India---Bangalore-IT-Capability-Centre/Junior-Frontend-QA-Engineer_JR28303/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 168,
    heading: "Software Engineer | ADP | Pune",
    link: "https://recruiting.adp.com/srccar/public/RTI.home?r=5001053431400&c=1130007&d=External-India&rb=INDEED&sid=101#/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 167,
    heading: "Software Engineer | NTT Data | Hyderabad, Bangalore",
    link: "https://careers.services.global.ntt/global/en/job/NTT1GLOBALR113463EXTERNALENGLOBAL/Associate-Software-Development-Engineer",
    image_url: "/static/img/hp.png",
  }, 
   {
    id: 166,
    heading: "Data Science Intern | TechBairn | Work From Home",
    link: "https://unstop.com/internships/data-science-internship-techbairn-1047860?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
    {
    id: 165,
    heading: "Engineer Intern | Kounsel | Work From Home",
    link: "https://www.linkedin.com/jobs/view/3961356993/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 164,
    heading: "DT Intern | GE Aerospace | Bengaluru",
    link: "https://jobs.gecareers.com/aviation/global/en/job/GE11GLOBALR3772705EXTERNALENGLOBAL/DT-Intern-Data-Science",
    image_url: "/static/img/hp.png",
  }, 
   {
    id: 163,
    heading: "Engineer Intern | Smartbear | Bengaluru",
    link: "https://boards.greenhouse.io/smartbear/jobs/5967735003",
    image_url: "/static/img/hp.png",
  },
    {
    id: 162,
    heading: "Tax Intern | EY | Bengaluru",
    link: "https://eyglobal.yello.co/jobs/XLJVAvo_lm40qIABCzm4cQ?job_board_id=c1riT--B2O-KySgYWsZO1Q",
    image_url: "/static/img/hp.png",
  },
    {
    id: 161,
    heading: "Application Intern | Upstox | Bengaluru",
    link: "https://jobs.lever.co/upstox/c050c398-67fa-4120-b7ce-a2817fcc9236",
    image_url: "/static/img/hp.png",
  },
   {
    id: 160,
    heading: "Recruitment Intern | Sprinto | Work From Home",
    link: "https://jobs.lever.co/Sprinto/cb7f399f-3a5f-4994-8551-a8bded28705a",
    image_url: "/static/img/hp.png",
  },
    {
    id: 159,
    heading: "HR Intern | CACTUS | India",
    link: "https://jobs.cactusglobal.com/jobs/1632?lang=en-us",
    image_url: "/static/img/hp.png",
  },
    {
    id: 158,
    heading: "Data Analytics Intern | AON | Bangalore",
    link: "https://india-careers-aon.icims.com/jobs/78676/job?mobile=false&width=940&height=500&bga=true&needsRedirect=false&jan1offset=330&jun1offset=330",
    image_url: "/static/img/hp.png",
  },
   {
    id: 157,
    heading: "Process Associate | IBM | Bengaluru",
    link: "https://www.naukri.com/job-listings-process-associate-risk-and-compliance-ibm-india-pvt-limited-bengaluru-0-to-1-years-020724913245",
    image_url: "/static/img/hp.png",
  },
    {
    id: 156,
    heading: "Financial Analyst | Infor | Hyderabad",
    link: "https://careers.infor.com/en_US/careers/JobDetail/Financial-Analyst-Associate/13238",
    image_url: "/static/img/hp.png",
  },
    {
    id: 155,
    heading: "Data Analyst | Capgemini | Pune",
    link: "https://jobs.capgemini.com/in-en/job/Pune-Data-Analyst-MH/1069933001/",
    image_url: "/static/img/hp.png",
  },
   {
    id: 154,
    heading: "SDET Intern | BlackBerry | Bengaluru",
    link: "https://bb.wd3.myworkdayjobs.com/en-US/BlackBerry/job/Bengaluru-India/Intern---SDET_20240449",
    image_url: "/static/img/hp.png",
  },
    {
    id: 153,
    heading: "Development Intern | Zoho | Kottarakkara",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1bc9a8b443ab578a0c2a130b45fdbb0a1",
    image_url: "/static/img/hp.png",
  },
    {
    id: 152,
    heading: "Graduate Intern | Intel | Bengaluru",
    link: "https://jobs.intel.com/en/job/-/-/599/66537757808",
    image_url: "/static/img/hp.png",
  },
   {
    id: 151,
    heading: "Software Engineer | Barclays | Pune",
    link: "https://search.jobs.barclays/job/-/-/13015/66876306384?src=JB-12860#anchor-description",
    image_url: "/static/img/hp.png",
  },
    {
    id: 150,
    heading: "Process Specialist | Cognizant | Bangalore",
    link: "https://careers.cognizant.com/global-en/jobs/00059084761/process-specialist-data/?src=SNS-102?JB-11500",
    image_url: "/static/img/hp.png",
  },
    {
    id: 149,
    heading: "Developer | Wipro | Hyderabad",
    link: "https://careers.wipro.com/careers-home/jobs/3084489",
    image_url: "/static/img/hp.png",
  },
   {
    id: 148,
    heading: "SDE | Urban Company | Gurgaon",
    link: "https://careers.urbancompany.com/jobDetail?id=9af0656f-fad3-421a-802e-caf1591f8a4f",
    image_url: "/static/img/hp.png",
  },
    {
    id: 147,
    heading: "Device Associate | Amazon | Chennai",
    link: "https://www.amazon.jobs/en/jobs/2679787/device-associate?cmpid=DA_INAD200785B",
    image_url: "/static/img/hp.png",
  },
    {
    id: 146,
    heading: "Operations Deal Manager | Microsoft | Bangalore",
    link: "https://jobs.careers.microsoft.com/global/en/job/1722966/Operations-Deal-Manager",
    image_url: "/static/img/hp.png",
  },
    {
    id: 145,
    heading: "Executive | KPMG | Gurgaon",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3/job/30015217",
    image_url: "/static/img/hp.png",
  },
    {
    id: 144,
    heading: "Graduate Engineer Trainee | Emerson | Pune",
    link: "https://hdjq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/24007423",
    image_url: "/static/img/hp.png",
  },
    {
    id: 143,
    heading: "DCO Trainee | Amazon | Mumbai",
    link: "https://www.amazon.jobs/en/jobs/2685391/dco-trainee?cmpid=DA_INAD200785B",
    image_url: "/static/img/hp.png",
  },
    {
    id: 142,
    heading: "IP Intern | Paytm | Mumbai",
    link: "https://jobs.lever.co/paytm/e86bbdd3-4de1-4d03-aada-17cc3ba3caf7",
    image_url: "/static/img/hp.png",
  },
    {
    id: 141,
    heading: "Data Analyst | NatWest Group | Bangalore, Gurugram",
    link: "https://rbs.wd3.myworkdayjobs.com/RBS/job/Bangalore/Digital-Analyst_R-00236427/",
    image_url: "/static/img/hp.png",
  },
    {
    id: 140,
    heading: "Systems Engineer | GE Vernova | Noida",
    link: "https://jobs.gecareers.com/vernova/global/en/job/R3768459/Systems-Engineer-System-Design",
    image_url: "/static/img/hp.png",
  },
    {
    id: 139,
    heading: "DevOps Engineer | McAfee | Work From Home",
    link: "https://careers.mcafee.com/global/en/job/MCAFGLOBALJR0031175ENGLOBALEXTERNAL/DevOps-Engineer-Remote",
    image_url: "/static/img/hp.png",
  },
    {
    id: 138,
    heading: "Associate Engineer | Harman  | Bangalore",
    link: "https://jobs.harman.com/en_US/careers/JobDetail/Associate-Engineer-AI-Data-and-Analytics/22891",
    image_url: "/static/img/hp.png",
  },
    {
    id: 137,
    heading: "Applications Engineer | Oracle | Hyderabad, Bengaluru",
    link: "https://careers.oracle.com/jobs/#en/sites/jobsearch/job/236961",
    image_url: "/static/img/hp.png",
  },
    {
    id: 136,
    heading: "Analyst | Goldman Sachs | Bangalore",
    link: "https://tinyurl.com/y9x9tk32",
    image_url: "/static/img/hp.png",
  },
    {
    id: 135,
    heading: "Consulting Internship | Deloitte | Mumbai",
    link: "https://tinyurl.com/2cj4s9fe",
    image_url: "/static/img/hp.png",
  },
    {
    id: 134,
    heading: "Data Analyst | S&P Global | Hyderabad",
    link: "https://tinyurl.com/4zp2mtk7",
    image_url: "/static/img/hp.png",
  },
    {
    id: 133,
    heading: "Support Associate | HP | Gurgaon",
    link: "https://unstop.com/jobs/customer-operations-support-associate-hewlett-packard-1050122?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
      {
    id: 132,
    heading: "Analyst Trainee | Deloitte | Hyderabad",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-Campus22-RFA-Analyst-Trainee-OTN/90340",
    image_url: "/static/img/hp.png",
  },
     {
    id: 131,
    heading: "New Associate | Accenture | Hyderabad",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=AIOC-S01523847_en&title=Trust%20%26%20Safety%20New%20Associate",
    image_url: "/static/img/hp.png",
  },             
   {
    id: 130,
    heading: "Executive | EXL | Pune",
    link: "https://exlcareers.peoplestrong.com/job/detail/EXL_E_1057057",
    image_url: "/static/img/hp.png",
  },
      {
    id: 129,
    heading: "Java Developer | CGI | Bangalore",
    link: "https://cgi.njoyn.com/CORP/xweb/xweb.asp?NTKN=c&clid=21001&Page=JobDetails&Jobid=J0524-1373&BRID=1134358&lang=1",
    image_url: "/static/img/hp.png",
  },
     {
    id: 128,
    heading: "QA Engineer | Zoho | Pan India",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614913581",
    image_url: "/static/img/hp.png",
  },             
    {
    id: 127,
    heading: "Software Engineer | AngularMinds | Pune",
    link: "https://www.angularminds.com/jobs/hiring-it-fresher-software-engineers-pune",
    image_url: "/static/img/hp.png",
  },
      {
    id: 126,
    heading: "Specialist Programmer | Infosys | Bangalore",
    link: "https://surveys.infosysapps.com/r/a/Infosys_SPhiring_24BATCH",
    image_url: "/static/img/hp.png",
  },
     {
    id: 125,
    heading: "Software Engineer | Amazon | Bangalore",
    link: "https://www.amazon.jobs/en/jobs/2671391/software-development-engineer",
    image_url: "/static/img/hp.png",
  },             
    {
    id: 124,
    heading: "Associate | DeshawIndia | Hyderabad",
    link: "https://www.deshawindia.com/careers/associate-qae-qte-fte-off-campus-2024-grads-5482",
    image_url: "/static/img/hp.png",
  },
      {
    id: 123,
    heading: "Application Developer | IBM | Pune",
    link: "https://careers.ibm.com/job/20359621/application-developer-cloud-fullstack-pune-in/",
    image_url: "/static/img/hp.png",
  },
     {
    id: 122,
    heading: "Graduate Intern | Intel | Bengaluru",
    link: "https://jobs.intel.com/en/job/-/-/599/64604293104",
    image_url: "/static/img/hp.png",
  },             
   {
    id: 121,
    heading: "SDE Intern | GeeksforGeeks | Noida",
    link: "https://www.geeksforgeeks.org/jobs/geeksforgeeks-software-engineer-backend-intern",
    image_url: "/static/img/hp.png",
  },
      {
    id: 120,
    heading: "Analyst | EY | Chennai",
    link: "https://careers.ey.com/ey/job/Chennai-Analyst-TAX-National-TAX-PAS-Mobility-Core-Chennai-TN-600113/1083753901/",
    image_url: "/static/img/hp.png",
  },
     {
    id: 119,
    heading: "DevOps Engineer | Wipro | Bengaluru",
    link: "https://careers.wipro.com/careers-home/jobs/3082201/job",
    image_url: "/static/img/hp.png",
  },             
   {
    id: 118,
    heading: "Associate | Wipro | Gurugram",
    link: "https://careers.wipro.com/careers-home/jobs/3080609?lang=en-us&previousLocale=en-US",
    image_url: "/static/img/hp.png",
  },
      {
    id: 117,
    heading: "Center Agent | ServiceNow | Hyderabad",
    link: "https://careers.servicenow.com/en/jobs/743999993946055/contact-center-agent/?trid=2d92f286-613b-4daf-9dfa-6340ffbecf73",
    image_url: "/static/img/hp.png",
  },
     {
    id: 116,
    heading: "Software Engineer | Microsoft | Bangalore",
    link: "https://jobs.careers.microsoft.com/us/en/job/1719114/Software-Engineer",
    image_url: "/static/img/hp.png",
  },             
   {
    id: 115,
    heading: "Trainee | Nagarro | Work From Home",
    link: "https://jobs.smartrecruiters.com/ni/Nagarro1/26076c22-eed6-47bf-a226-e819c6efb9d8-trainee",
    image_url: "/static/img/hp.png",
  },
      {
    id: 114,
    heading: "Technology Engineer | Amdocs | Pune",
    link: "https://jobs.amdocs.com/careers/job/563430997294976",
    image_url: "/static/img/hp.png",
  },
     {
    id: 113,
    heading: "Analyst | EY  | Bengaluru",
    link: "https://careers.ey.com/ey/job/Bengaluru-GMS_Compliance_Analyst-Bangalore-KA-560016/1082139201/",
    image_url: "/static/img/hp.png",
  },               
   {
    id: 112,
    heading: "Associate | Concentrix | Gurgaon",
    link: "https://apply.concentrix.com/global/en/job/CONCGLOBALR1499686EXTERNALENGLOBAL/Associate-Real-Time-Management",
    image_url: "/static/img/hp.png",
  },
      {
    id: 111,
    heading: "Technical Analyst | Oracle | Across India",
    link: "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/218870?lastSelectedFacet=LOCATIONS&selectedLocationsFacet=300000000106947",
    image_url: "/static/img/hp.png",
  },
     {
    id: 110,
    heading: "Support Practitioner | Accenture  | Bengaluru",
    link: "https://www.accenture.com/in-en/careers/jobdetails?src=LINKEDINJP&id=ATCI-4380570-S1722569_en",
    image_url: "/static/img/hp.png",
  },               
  {
    id: 109,
    heading: "Business Analytics | American Express | Gurgaon",
    link: "https://aexp.eightfold.ai/careers/job/22394470",
    image_url: "/static/img/hp.png",
  },
      {
    id: 108,
    heading: "Software Engineer | IKEA | Bengaluru",
    link: "https://ikea.avature.net/en_BW/External/JobDetail?id=239051#",
    image_url: "/static/img/hp.png",
  },
     {
    id: 107,
    heading: "Backend Developer | IBM  | Bangalore",
    link: "https://careers.ibm.com/job/20432303/backend-developer-bangalore-in/",
    image_url: "/static/img/hp.png",
  },                
  {
    id: 106,
    heading: "Desk Analyst | Wipro | Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3084629?lang=en-us&previousLocale=en-US",
    image_url: "/static/img/hp.png",
  },
      {
    id: 105,
    heading: "Software Engineer | PayPal | Work From Home",
    link: "https://paypal.eightfold.ai/careers?pid=274900373144&Brand=PayPal&Employment%20Type=full%20time&Type%20of%20Work=remote&domain=paypal.com&sort_by=relevance&triggerGoButton=false",
    image_url: "/static/img/hp.png",
  },
     {
    id: 104,
    heading: "Software Engineer | Jio  | Mumbai",
    link: "https://careers.jio.com/frmjobdescription.aspx?JBTITLE=n2bW34EnFXxoNmUsKuvYSA==&jbID=B1uevVccgI/5XYrQWkeXPA==&funcCode=am1AraTXtX4/W/EJK6dzzw==",
    image_url: "/static/img/hp.png",
  },
          {
    id: 103,
    heading: "Intern | Airbus | Bangalore",
    link: "https://ag.wd3.myworkdayjobs.com/en-US/Airbus/job/Bangalore-Area/Intern---Airframe---Internal-Flows---Analytics_JR10273256",
    image_url: "/static/img/hp.png",
  },
      {
    id: 102,
    heading: "Software Engineer | JPMorgan | Bengaluru",
    link: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210512342",
    image_url: "/static/img/hp.png",
  },
     {
    id: 101,
    heading: "Backend Engineer Intern | Peakflo  | Work From Home",
    link: "https://www.ycombinator.com/companies/peakflo/jobs/xiiq0Kj-backend-engineer-internship-remote",
    image_url: "/static/img/hp.png",
  },
         {
    id: 100,
    heading: "Trainee | Infosys | Freshers",
    link: "https://tinyurl.com/infosys-freshers",
    image_url: "/static/img/hp.png",
  },
      {
    id: 99,
    heading: "Trainee | HBC | Bangalore",
    link: "https://www.hbcindiacareers.com/en/job/240001KM?src=JB-10060",
    image_url: "/static/img/hp.png",
  },
     {
    id: 98,
    heading: "Data Scientist  | HP  | Bangalore",
    link: "https://hp.wd5.myworkdayjobs.com/en-US/ExternalCareerSite/job/Bangalore-Karnataka-India/Data-Scientist_3136994-1",
    image_url: "/static/img/hp.png",
  },
    {
    id: 97,
    heading: "Associate Fresher | Genpact | Bangalore",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=ITO081181",
    image_url: "/static/img/hp.png",
  },
      {
    id: 96,
    heading: "Analyst | WNS | Work From Home",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999987647463-analyst-rna?trid=bb2572dc-93af-47bd-9bb1-9f049abba39c",
    image_url: "/static/img/hp.png",
  },
     {
    id: 95,
    heading: "Associate  | PwC  | Bangalore",
    link: "https://www.pwc.com/gx/en/careers/student-job-search/description.html?wdjobreqid=458884WD&wdcountry=IND&jobtitle=Acceleration%20Center%20-%20Business%20Services%20-%20Product%20&%20Technology%20-%20Associate%20-%202024&wdjobsite=Global_Campus_Careers",
    image_url: "/static/img/hp.png",
  },
    {
    id: 94,
    heading: "Business Analyst Intern | Amazon | Bangalore",
    link: "https://www.amazon.jobs/en/jobs/2662463/business-analyst-intern-row-sharp-team?cmpid=DA_INAD200785B",
    image_url: "/static/img/hp.png",
  },
      {
    id: 93,
    heading: "QA Intern | Smallcase | Bengaluru",
    link: "https://smallcase.freshteam.com/jobs/UaUOFctFidkT/qa-internship",
    image_url: "/static/img/hp.png",
  },
     {
    id: 92,
    heading: "Java Developer | Volvo Group  | Bangalore",
    link: "https://jobs.volvogroup.com/job/Bangalore-ExcelHER_Java-Developer-562122/978610555/?feedId=361555&utm_source=linkedin",
    image_url: "/static/img/hp.png",
  },
    {
    id: 91,
    heading: "Software Engineer Intern | IBM | Bangalore/Pune",
    link: "https://careers.ibm.com/job/20481519/intern-software-engineer-remote/",
    image_url: "/static/img/hp.png",
  },
      {
    id: 90,
    heading: "Java Developer Intern | Freshers | Full Time",
    link: "https://unstop.com/internships/java-developer-internship-parul-university-pu-vadodara-1008079?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
     {
    id: 89,
    heading: "TCS is Hiring FRESHERS | Any Graduate | 2023 - 2024",
    link: "https://www.tcs.com/careers/india/tcs-smart-hiring-2024",
    image_url: "/static/img/hp.png",
  },
    {
    id: 88,
    heading: "Operations Expert | Apple | Mumbai/Delhi",
    link: "https://jobs.apple.com/en-in/details/200314033/in-operations-expert",
    image_url: "/static/img/hp.png",
  },
    {
    id: 87,
    heading: "Business Analyst | Citi Bank | Bangalore",
    link: "https://jobs.citi.com/job/-/-/287/65497931696",
    image_url: "/static/img/hp.png",
  },
    {
    id: 86,
    heading: "Support Specialist | Revolut | WORK FROM HOME",
    link: "https://www.revolut.com/careers/position/support-specialist-phone-f390b2d0-cafa-4cda-8e0d-901d29bdeed7/",
    image_url: "/static/img/hp.png",
  },
               {
    id: 85,
    heading: "Costumer Solution Engineer | Google | Bangalore/Mumbai",
    link: "https://www.google.com/about/careers/applications/jobs/results/100681580478898886-customer-solutions-engineer-gtech?location=India&target_level=EARLY",
    image_url: "/static/img/hp.png",
  },
               {
    id: 84,
    heading: "Associate | WNS | Bangalore",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999968409093-associate-sr-associate",
    image_url: "/static/img/hp.png",
  },
               {
    id: 83,
    heading: "Internal Audit Analyst | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10017976",
    image_url: "/static/img/hp.png",
  },
           {
    id: 82,
    heading: "Developer | Wipro | Bangalore/Hyderabad",
    link: "https://careers.wipro.com/careers-home/jobs/3070541/job",
    image_url: "/static/img/hp.png",
  },
           {
    id: 81,
    heading: "Consulting Internships | Deloitte | Bangalore",
    link: "https://jobsindia.deloitte.com/job/Bengaluru-Consulting-Internships/25188944/",
    image_url: "/static/img/hp.png",
  },
           {
    id: 80,
    heading: "Associate Software Engineer | NTT Data | Bangalore/Hyderabad",
    link: "https://careers.services.global.ntt/global/en/job/NTT1GLOBALR113463EXTERNALENGLOBAL/Associate-Software-Development-Engineer",
    image_url: "/static/img/hp.png",
  },
           {
    id: 79,
    heading: "CSE | Tech Mahindra | Work From Home",
    link: "https://www.naukri.com/job-listings-customer-service-executive-tech-mahindra-kolkata-0-to-5-years-160524010559?src=cluster&sid=17160587801013797_1&xp=1&px=1",
    image_url: "/static/img/hp.png",
  },
         {
    id: 78,
    heading: "Quality Analyst | Welocalize | Work From Home",
    link: "https://unstop.com/jobs/ads-quality-rater-hindi-welocalize-994632?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
          {
    id: 77,
    heading: "Software Intern | Intel | Bangalore",
    link: "https://jobs.intel.com/en/job/-/-/599/64604293104",
    image_url: "/static/img/hp.png",
  },
          {
    id: 76,
    heading: "Quality Engineer | Accenture | Bangalore",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4366344-S1689605_en",
    image_url: "/static/img/hp.png",
  },
          {
    id: 75,
    heading: "Software Engineer | Cognizant | Bangalore",
    link: "https://careers.cognizant.com/global-en/jobs/00058596351/software-engineer/?src=SNS-102?JB-11500&utm_source=Software_Engineer_unstop&utm_medium=listing&utm_campaign=unstop",
    image_url: "/static/img/hp.png",
  },
       {
    id: 74,
    heading: "Technical Analyst 1 | Oracle | Bangalore",
    link: "https://careers.oracle.com/jobs/#en/sites/jobsearch/job/232413/?lastSelectedFacet=AttributeChar6&location=India&locationId=300000000106947&locationLevel=country&mode=location&selectedFlexFieldsFacets=%2522AttributeChar6%257C0+to+2%252B+years%2522",
    image_url: "/static/img/hp.png",
  },
       {
    id: 73,
    heading: "Software Intern | Salesforce | Bangalore / Hyderabad",
    link: "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site/job/India---Hyderabad/Intern_JR250704",
    image_url: "/static/img/hp.png",
  },
       {
    id: 72,
    heading: "Intern | Ericsson | Noida",
    link: "https://jobs.ericsson.com/careers/job/563121759719808",
    image_url: "/static/img/hp.png",
  },
      {
    id: 71,
    heading: "Advisor | PhonePe | Bangalore",
    link: "https://boards.greenhouse.io/embed/job_app?token=5958724003",
    image_url: "/static/img/hp.png",
  },
      {
    id: 70,
    heading: "Analyst | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3/job/30014533",
    image_url: "/static/img/hp.png",
  },
      {
    id: 69,
    heading: "Software Developer | ZOHO | Chennai",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1d818f12a6a00e375c49160b9189518c4",
    image_url: "/static/img/hp.png",
  },
   {
    id: 68,
    heading: "TCS is Hiring Through TCS NQT | Freshers | 11 May 2024 ",
    link: "https://www.tcsion.com/hub/national-qualifier-test/",
    image_url: "/static/img/hp.png",
  },
              {
    id: 67,
    heading: "Software Engineer | Google | Hyderabad",
    link: "https://www.google.com/about/careers/applications/jobs/results/128616549612167878-software-engineer",
    image_url: "/static/img/hp.png",
  },
              {
    id: 69,
    heading: "Associate System Engineer | IBM | Mumbai/Pune/Hyderabad",
    link: "https://careers.ibm.com/job/19344653/associate-system-engineer-remote/",
    image_url: "/static/img/hp.png",
  },
              {
    id: 68,
    heading: "Sales Development Representative | Canonical | Work From Home",
    link: "https://boards.greenhouse.io/canonicaljobs/jobs/5912451?gh_src=d6d6cc6d1us",
    image_url: "/static/img/hp.png",
  },
           {
    id: 67,
    heading: "Software Engineer | Coinbase | Across India",
    link: "https://www.coinbase.com/en-gb/careers/positions/5920858?gh_jid=5920858",
    image_url: "/static/img/hp.png",
  },
           {
    id: 66,
    heading: "Application Developer | Accenture | Bangalore",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4308223-S1668147_en",
    image_url: "/static/img/hp.png",
  },
           {
    id: 65,
    heading: "Cyber Defence Analyst | Groww | Bangalore",
    link: "https://groww.skillate.com/jobs/54390",
    image_url: "/static/img/hp.png",
  },
       {
    id: 64,
    heading: "Assistant Manager | Genpact | Gurgaon",
    link: "https://unstop.com/jobs/assistant-manager-genpact-973571?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
       {
    id: 63,
    heading: "System Engineer | Wipro | Bangalore",
    link: "https://unstop.com/jobs/system-engineer-wipro-970569?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
       {
    id: 62,
    heading: "Quality Assurance Analyst | Deloitte | Hyderabad",
    link: "https://unstop.com/jobs/quality-assurance-analyst-deloitte-970487?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
       {
    id: 61,
    heading: "Analyst | Wipro | Bangalore",
    link: "https://careers.wipro.com/careers-home/jobs/3071006?lang=en-us&previousLocale=en-US",
    image_url: "/static/img/hp.png",
  },
       {
    id: 60,
    heading: "Junior Analyst | BCG Group | Delhi",
    link: "https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?PageType=JobDetails&partnerid=25811&siteid=5185&Areq=22832BR#jobDetails=860935_5185",
    image_url: "/static/img/hp.png",
  },
       {
    id: 59,
    heading: "Intern | NetApp | Bangalore",
    link: "https://careers.netapp.com/job/bengaluru/intern/27600/64145961392",
    image_url: "/static/img/hp.png",
  },
      {
    id: 58,
    heading: "Trainee | TCS BPS | Multiple Location",
    link: "https://www.tcs.com/careers/india/tcs-bps-fresher-hiring-2024",
    image_url: "/static/img/hp.png",
  },
      {
    id: 57,
    heading: "Graduate Engineer Trainee | NTT DATA | Bangalore",
    link: "https://careers.services.global.ntt/global/en/job/R-110031/apply",
    image_url: "/static/img/hp.png",
  },
      {
    id: 56,
    heading: "Associate | WNS | Bangalore",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999968409093-associate-sr-associate",
    image_url: "/static/img/hp.png",
  },
              {
    id: 55,
    heading: "Software Engineering | Goldman Sachs | Bangalore",
    link: "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/LateralHiring/job/124502",
    image_url: "/static/img/hp.png",
  },
              {
    id: 54,
    heading: "Process Advisor | Barclays | Pune",
    link: "https://search.jobs.barclays/job/pune/process-advisor/13015/63867153760",
    image_url: "/static/img/hp.png",
  },
              {
    id: 53,
    heading: "Trainee | Siemens | Bangalore",
    link: "https://jobs.siemens.com/careers/job?domain=siemens.com&pid=563156119319852&domain=siemens.com",
    image_url: "/static/img/hp.png",
  },
           {
    id: 52,
    heading: "Analyst | HSBC | Bangalore",
    link: "https://mycareer.hsbc.com/en_GB/external/PipelineDetail/Analyst-Data-Governance-GSC-S/216031?src=JB-257546",
    image_url: "/static/img/hp.png",
  },
           {
    id: 51,
    heading: "Web Developer | Lenovo | Bangalore",
    link: "https://jobs.lenovo.com/en_US/careers/JobDetail/Web-Developer/55803#",
    image_url: "/static/img/hp.png",
  },
           {
    id: 50,
    heading: "Tech Internship | Agoda | Gurgaon",
    link: "https://careersatagoda.com/job/5417820-tech-internship-2024-india-based-gurgaon-office/",
    image_url: "/static/img/hp.png",
  },
          {
    id: 49,
    heading: "Business Technology Analyst | Deloitte | Hyderabad",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-EH24-Tax-Business-Technology-Analyst-SAP-FI-SD-Fresher-NSE/176139",
    image_url: "/static/img/hp.png",
  },
          {
    id: 48,
    heading: "Associate | Sutherland | Chennai",
    link: "https://unstop.com/jobs/associate-customer-service-sutherland-global-952364?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
          {
    id: 47,
    heading: "Product Marketers | ZOHO | Chennai",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1113aee614efa3264984aa32841436332",
    image_url: "/static/img/hp.png",
  },
        {
    id: 46,
    heading: "Business Analyst | Infosys | Bangalore/Hybrid",
    link: "https://career.infosys.com/jobdesc?jobReferenceCode=INFSYS-NAUKRI-178682&sourceId=4001",
    image_url: "/static/img/hp.png",
  },
        {
    id: 45,
    heading: "Platform Support Associate | Accenture | Hyderabad",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=AIOC-S01513200_en&title=Platform%20Support%20New%20Associate",
    image_url: "/static/img/hp.png",
  },
        {
    id: 44,
    heading: "Quality Engineer | Service Now| Hyderabad",
    link: "https://unstop.com/jobs/software-quality-engineer-servicenow-946323?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
     {
    id: 43,
    heading: "Engineer 1 | American Express | Bangalore/Hybrid",
    link: "https://aexp.eightfold.ai/careers/job/21092401?domain=aexp.com",
    image_url: "/static/img/hp.png",
  },
     {
    id: 42,
    heading: "Associate Software Developer | Cyntexa | Jaipur",
    link: "https://cyntexa.com/careers/associate-software-developer/",
    image_url: "/static/img/hp.png",
  },
     {
    id: 41,
    heading: "Data Engineer | Pearson | Bangalore",
    link: "https://pearson.jobs/bangalore-ind/data-engineer-intern/A7DBAA9089EF49D79B56F24697A6155A/job/",
    image_url: "/static/img/hp.png",
  },
             {
    id: 40,
    heading: "Support Analyst | Revolut | Work From Home",
    link: "https://www.revolut.com/careers/position/support-specialist-identity-and-verification-analyst-35ee6d79-acf3-4dcc-8544-19d8115f2ed6/",
    image_url: "/static/img/hp.png",
  },
             {
    id: 39,
    heading: "Software Engineer | Cognizant | Bangalore",
    link: "https://careers.cognizant.com/global/en/job/COGNGLOBAL00058595801/Software-Engineer",
    image_url: "/static/img/hp.png",
  },
             {
    id: 38,
    heading: "Technical Support Engineer | IBM | Bangalore",
    link: "https://krb-sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26059&siteid=5016&PageType=JobDetails&jobid=730146#jobDetails=730146_5016",
    image_url: "/static/img/hp.png",
  },
         {
    id: 37,
    heading: "Process Associate | Genpact | Noida",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?src=DS-10971&job=1322997",
    image_url: "/static/img/hp.png",
  },
         {
    id: 36,
    heading: "Financial Analyst | Alight | Work From Home",
    link: "https://careers.alight.com/us/en/job/ALIGUSR28009EXTERNALENUS/Financial-Analyst-I",
    image_url: "/static/img/hp.png",
  },
         {
    id: 35,
    heading: "Software Engineer | Infor | Bangalore",
    link: "https://careers.infor.com/en_US/careers/JobDetail/Software-Engineer-Associate/13323",
    image_url: "/static/img/hp.png",
  },
        {
    id: 34,
    heading: "Data Analyst | Walmart | Bangalore",
    link: "https://walmart.wd5.myworkdayjobs.com/en-US/WalmartExternal/job/DATA-ANALYST-II--DATA-ANALYTICS_R-1796887-1",
    image_url: "/static/img/hp.png",
  },
        {
    id: 33,
    heading: "Program Analyst | WNS | Mumbai",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999978597288-ref31776o-end-user-computing-desktop-support-mumbai-wfo-senior-program-analyst-eit",
    image_url: "/static/img/hp.png",
  },
        {
    id: 32,
    heading: "Analyst | Morgan Stanley | Mumbai",
    link: "https://morganstanley.eightfold.ai/careers?pid=549777250362&domain=morganstanley.com&sort_by=relevance",
    image_url: "/static/img/hp.png",
  },
       {
    id: 31,
    heading: "Customer Executive | Groww | Work From Home",
    link: "https://groww.skillate.com/jobs/54143",
    image_url: "/static/img/hp.png",
  },
       {
    id: 30,
    heading: "QA Engineer | Peakflo | Work From Home",
    link: "https://app.dover.io/apply/peakflo/c785fb54-e416-4748-879a-313fdb1e6f7a?rs=42706078",
    image_url: "/static/img/hp.png",
  },
       {
    id: 29,
    heading: "Cloud Specialist | Hyland | Work From Home",
    link: "https://careers-hyland.icims.com/jobs/11504/cloud-specialist-2/job?mode=job&iis=Job%2BBoard&mobile=true&width=390&height=669&bga=true&needsRedirect=false&jan1offset=330&jun1offset=330",
    image_url: "/static/img/hp.png",
  },
     {
    id: 28,
    heading: "Associate Analyst | EY | Work From Home",
    link: "https://unstop.com/jobs/associate-analyst-ey-ernst-young-948846?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
     {
    id: 27,
    heading: "SW Test Engineer | Amdocs | Pune",
    link: "https://jobs.amdocs.com/careers/job/563430997179581",
    image_url: "/static/img/hp.png",
  },
     {
    id: 26,
    heading: "Trainee Engineer | NTT Data | Mumbai",
    link: "https://careers.services.global.ntt/global/en/job/NTT1GLOBALR112898EXTERNALENGLOBAL/Trainee-Engineer",
    image_url: "/static/img/hp.png",
  },
     {
    id: 25,
    heading: "Data Analyst | Wipro | Hyderabad",
    link: "https://careers.wipro.com/careers-home/jobs/3066940",
    image_url: "/static/img/hp.png",
  },
     {
    id: 24,
    heading: "Salesforce Developer | Pearson | Bangalore",
    link: "https://pearson.jobs/bangalore-ind/salesforce-developer-intern/FCF1D1167E8A48CBA486F65F3F1C8296/job/?vs=1554",
    image_url: "/static/img/hp.png",
  },
     {
    id: 23,
    heading: "Graduate Engineer Trainee | Invesco | Hyderabad",
    link: "https://invesco.wd1.myworkdayjobs.com/en-US/intelliflo/job/Hyderabad-Telangana/Graduate-Engineer-Trainee_R-5629",
    image_url: "/static/img/hp.png",
  },
     {
    id: 22,
    heading: "CXQO Associate | Amazon | Hyderabad",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/dirc1/apply/?event=14050&job=58038",
    image_url: "/static/img/hp.png",
  },
  {
    id: 21,
    heading: "Domain Trainee | Genpact | Jaipur",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=INS023413",
    image_url: "/static/img/hp.png",
  },
  {
    id: 20,
    heading: "QA Engineer | ZOHO Corp | Chennai",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614913581",
    image_url: "/static/img/hp.png",
  },
  {
    id: 19,
    heading: "Consultant Internship | Deloitte | Bangalore",
    link: "https://jobsindia.deloitte.com/job/Bengaluru-Consulting-Internship/23914944/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 18,
    heading: "Software Development Engineer | Urban Company | Gurgaon",
    link: "https://careers.urbancompany.com/jobDetail?id=eb369381-1cfe-432f-affc-12070d83a2c6",
    image_url: "/static/img/hp.png",
  },
  {
    id: 17,
    heading: "Analyst | EY | Noida",
    link: "https://careers.ey.com/ey/job/Noida-Analyst-Forensics-National-ASU-Forensics-Investigations-&-Compliance-Noida-UP-201304/1003553001/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 16,
    heading: "Quality Analyst | Revolut | Work From Home",
    link: "https://www.revolut.com/en-IN/careers/position/quality-assurance-analyst-0f7bfdfb-6fd1-4fbe-b586-f62f84536fa9/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 15,
    heading: "Software Engineer Intern | NIKE | Bangalore",
    link: "https://jobs.nike.com/job/R-24752?cp=76060516106_aff_je6NUbpObpQ&ranMID=41134&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-UmBg0FI_AoHwGdLO5ac13w",
    image_url: "/static/img/hp.png",
  },
  {
    id: 14,
    heading: "iOS Developer | Meesho | Bangalore",
    link: "https://jobs.lever.co/meesho/6e0e5074-e1bb-41c6-89bb-2c20d36d4b0f/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 13,
    heading: "Software Engineer | Microsoft | Bangalore / WFH",
    link: "https://jobs.careers.microsoft.com/global/en/job/1704435/Software-Engineer",
    image_url: "/static/img/hp.png",
  },
  {
    id: 12,
    heading: "Quality Associate | Amazon | Hyderabad",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=58218&e=14250",
    image_url: "/static/img/hp.png",
  },
  {
    id: 11,
    heading: "Associate Consultant | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10015744",
    image_url: "/static/img/hp.png",
  },
  {
    id: 10,
    heading: "Associate Software Engineer | Oracle | Bangalore",
    link: "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/233846",
    image_url: "/static/img/hp.png",
  },
  {
    id: 9,
    heading: "Software Development Engineer | Adobe | Noida",
    link: "https://careers.adobe.com/us/en/job/ADOBUSR145089EXTERNALENUS/Software-Development-Engineer",
    image_url: "/static/img/hp.png",
  },
  {
    id: 8,
    heading: "Developer Associate | SAP | Bangalore",
    link: "https://jobs.sap.com/job/Bangalore-Developer-Associate-KA-560066/1055158601/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 7,
    heading: "Software Developer | ZOHO | Pan India",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614929615",
    image_url: "/static/img/hp.png",
  },
  {
    id: 6,
    heading: "Software Engineer | Myntra | Bangalore",
    link: "https://boards.greenhouse.io/myntra/jobs/7216939002?",
    image_url: "/static/img/hp.png",
  },
  {
    id: 5,
    heading: "Process Analyst | IBM | Bangalore",
    link: "https://www.naukri.com/job-listings-process-analyst-recruitment-ibm-india-pvt-limited-bengaluru-0-to-3-years-260324910641?src=jobsearchDesk&sid=17115543450314158&xp=10&px=1&nignbevent_src=jobsearchDeskGNB",
    image_url: "/static/img/hp.png",
  },
  {
    id: 4,
    heading: "System Analyst | Nielsen | Bangalore",
    link: "https://jobs.lever.co/nielsen/fed9aa65-af08-42b3-b740-441e4da27f02",
    image_url: "/static/img/hp.png",
  },
  {
    id: 3,
    heading: "Development Associate | Accenture | Pan India",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/25377/job-details",
    image_url: "/static/img/jnj.png",
  },
  {
    id: 2,
    heading: "Technology Analyst | Deloitte | Hyderabad/Pune",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-EH24-TAX-GESTC-B2B-Helpdesk-BTA-Hyd-Pun/140758",
    image_url: "/static/img/infor.png",
  },
  {
    id: 1,
    heading: "Data Analyst | Walmart | Bangalore",
    link: "https://walmart.wd5.myworkdayjobs.com/en-US/WalmartExternal/job/DATA-ANALYST-II--DATA-ANALYTICS_R-1796887-1",
    image_url: "/static/img/Deloitte_Logo.png",
  },
];
