export const JobList: Job[] = [
      {
    id: 96,
    heading: "Analyst | WNS | Work From Home",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999987647463-analyst-rna?trid=bb2572dc-93af-47bd-9bb1-9f049abba39c",
    image_url: "/static/img/hp.png",
  },
     {
    id: 95,
    heading: "Associate  | PwC  | Bangalore",
    link: "https://www.pwc.com/gx/en/careers/student-job-search/description.html?wdjobreqid=458884WD&wdcountry=IND&jobtitle=Acceleration%20Center%20-%20Business%20Services%20-%20Product%20&%20Technology%20-%20Associate%20-%202024&wdjobsite=Global_Campus_Careers",
    image_url: "/static/img/hp.png",
  },
    {
    id: 94,
    heading: "Business Analyst Intern | Amazon | Bangalore",
    link: "https://www.amazon.jobs/en/jobs/2662463/business-analyst-intern-row-sharp-team?cmpid=DA_INAD200785B",
    image_url: "/static/img/hp.png",
  },
      {
    id: 93,
    heading: "QA Intern | Smallcase | Bengaluru",
    link: "https://smallcase.freshteam.com/jobs/UaUOFctFidkT/qa-internship",
    image_url: "/static/img/hp.png",
  },
     {
    id: 92,
    heading: "Java Developer | Volvo Group  | Bangalore",
    link: "https://jobs.volvogroup.com/job/Bangalore-ExcelHER_Java-Developer-562122/978610555/?feedId=361555&utm_source=linkedin",
    image_url: "/static/img/hp.png",
  },
    {
    id: 91,
    heading: "Software Engineer Intern | IBM | Bangalore/Pune",
    link: "https://careers.ibm.com/job/20481519/intern-software-engineer-remote/",
    image_url: "/static/img/hp.png",
  },
      {
    id: 90,
    heading: "Java Developer Intern | Freshers | Full Time",
    link: "https://unstop.com/internships/java-developer-internship-parul-university-pu-vadodara-1008079?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
     {
    id: 89,
    heading: "TCS is Hiring FRESHERS | Any Graduate | 2023 - 2024",
    link: "https://www.tcs.com/careers/india/tcs-smart-hiring-2024",
    image_url: "/static/img/hp.png",
  },
    {
    id: 88,
    heading: "Operations Expert | Apple | Mumbai/Delhi",
    link: "https://jobs.apple.com/en-in/details/200314033/in-operations-expert",
    image_url: "/static/img/hp.png",
  },
    {
    id: 87,
    heading: "Business Analyst | Citi Bank | Bangalore",
    link: "https://jobs.citi.com/job/-/-/287/65497931696",
    image_url: "/static/img/hp.png",
  },
    {
    id: 86,
    heading: "Support Specialist | Revolut | WORK FROM HOME",
    link: "https://www.revolut.com/careers/position/support-specialist-phone-f390b2d0-cafa-4cda-8e0d-901d29bdeed7/",
    image_url: "/static/img/hp.png",
  },
               {
    id: 85,
    heading: "Costumer Solution Engineer | Google | Bangalore/Mumbai",
    link: "https://www.google.com/about/careers/applications/jobs/results/100681580478898886-customer-solutions-engineer-gtech?location=India&target_level=EARLY",
    image_url: "/static/img/hp.png",
  },
               {
    id: 84,
    heading: "Associate | WNS | Bangalore",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999968409093-associate-sr-associate",
    image_url: "/static/img/hp.png",
  },
               {
    id: 83,
    heading: "Internal Audit Analyst | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10017976",
    image_url: "/static/img/hp.png",
  },
           {
    id: 82,
    heading: "Developer | Wipro | Bangalore/Hyderabad",
    link: "https://careers.wipro.com/careers-home/jobs/3070541/job",
    image_url: "/static/img/hp.png",
  },
           {
    id: 81,
    heading: "Consulting Internships | Deloitte | Bangalore",
    link: "https://jobsindia.deloitte.com/job/Bengaluru-Consulting-Internships/25188944/",
    image_url: "/static/img/hp.png",
  },
           {
    id: 80,
    heading: "Associate Software Engineer | NTT Data | Bangalore/Hyderabad",
    link: "https://careers.services.global.ntt/global/en/job/NTT1GLOBALR113463EXTERNALENGLOBAL/Associate-Software-Development-Engineer",
    image_url: "/static/img/hp.png",
  },
           {
    id: 79,
    heading: "CSE | Tech Mahindra | Work From Home",
    link: "https://www.naukri.com/job-listings-customer-service-executive-tech-mahindra-kolkata-0-to-5-years-160524010559?src=cluster&sid=17160587801013797_1&xp=1&px=1",
    image_url: "/static/img/hp.png",
  },
         {
    id: 78,
    heading: "Quality Analyst | Welocalize | Work From Home",
    link: "https://unstop.com/jobs/ads-quality-rater-hindi-welocalize-994632?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
          {
    id: 77,
    heading: "Software Intern | Intel | Bangalore",
    link: "https://jobs.intel.com/en/job/-/-/599/64604293104",
    image_url: "/static/img/hp.png",
  },
          {
    id: 76,
    heading: "Quality Engineer | Accenture | Bangalore",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4366344-S1689605_en",
    image_url: "/static/img/hp.png",
  },
          {
    id: 75,
    heading: "Software Engineer | Cognizant | Bangalore",
    link: "https://careers.cognizant.com/global-en/jobs/00058596351/software-engineer/?src=SNS-102?JB-11500&utm_source=Software_Engineer_unstop&utm_medium=listing&utm_campaign=unstop",
    image_url: "/static/img/hp.png",
  },
       {
    id: 74,
    heading: "Technical Analyst 1 | Oracle | Bangalore",
    link: "https://careers.oracle.com/jobs/#en/sites/jobsearch/job/232413/?lastSelectedFacet=AttributeChar6&location=India&locationId=300000000106947&locationLevel=country&mode=location&selectedFlexFieldsFacets=%2522AttributeChar6%257C0+to+2%252B+years%2522",
    image_url: "/static/img/hp.png",
  },
       {
    id: 73,
    heading: "Software Intern | Salesforce | Bangalore / Hyderabad",
    link: "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site/job/India---Hyderabad/Intern_JR250704",
    image_url: "/static/img/hp.png",
  },
       {
    id: 72,
    heading: "Intern | Ericsson | Noida",
    link: "https://jobs.ericsson.com/careers/job/563121759719808",
    image_url: "/static/img/hp.png",
  },
      {
    id: 71,
    heading: "Advisor | PhonePe | Bangalore",
    link: "https://boards.greenhouse.io/embed/job_app?token=5958724003",
    image_url: "/static/img/hp.png",
  },
      {
    id: 70,
    heading: "Analyst | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3/job/30014533",
    image_url: "/static/img/hp.png",
  },
      {
    id: 69,
    heading: "Software Developer | ZOHO | Chennai",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1d818f12a6a00e375c49160b9189518c4",
    image_url: "/static/img/hp.png",
  },
   {
    id: 68,
    heading: "TCS is Hiring Through TCS NQT | Freshers | 11 May 2024 ",
    link: "https://www.tcsion.com/hub/national-qualifier-test/",
    image_url: "/static/img/hp.png",
  },
              {
    id: 67,
    heading: "Software Engineer | Google | Hyderabad",
    link: "https://www.google.com/about/careers/applications/jobs/results/128616549612167878-software-engineer",
    image_url: "/static/img/hp.png",
  },
              {
    id: 69,
    heading: "Associate System Engineer | IBM | Mumbai/Pune/Hyderabad",
    link: "https://careers.ibm.com/job/19344653/associate-system-engineer-remote/",
    image_url: "/static/img/hp.png",
  },
              {
    id: 68,
    heading: "Sales Development Representative | Canonical | Work From Home",
    link: "https://boards.greenhouse.io/canonicaljobs/jobs/5912451?gh_src=d6d6cc6d1us",
    image_url: "/static/img/hp.png",
  },
           {
    id: 67,
    heading: "Software Engineer | Coinbase | Across India",
    link: "https://www.coinbase.com/en-gb/careers/positions/5920858?gh_jid=5920858",
    image_url: "/static/img/hp.png",
  },
           {
    id: 66,
    heading: "Application Developer | Accenture | Bangalore",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4308223-S1668147_en",
    image_url: "/static/img/hp.png",
  },
           {
    id: 65,
    heading: "Cyber Defence Analyst | Groww | Bangalore",
    link: "https://groww.skillate.com/jobs/54390",
    image_url: "/static/img/hp.png",
  },
       {
    id: 64,
    heading: "Assistant Manager | Genpact | Gurgaon",
    link: "https://unstop.com/jobs/assistant-manager-genpact-973571?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
       {
    id: 63,
    heading: "System Engineer | Wipro | Bangalore",
    link: "https://unstop.com/jobs/system-engineer-wipro-970569?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
       {
    id: 62,
    heading: "Quality Assurance Analyst | Deloitte | Hyderabad",
    link: "https://unstop.com/jobs/quality-assurance-analyst-deloitte-970487?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
       {
    id: 61,
    heading: "Analyst | Wipro | Bangalore",
    link: "https://careers.wipro.com/careers-home/jobs/3071006?lang=en-us&previousLocale=en-US",
    image_url: "/static/img/hp.png",
  },
       {
    id: 60,
    heading: "Junior Analyst | BCG Group | Delhi",
    link: "https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?PageType=JobDetails&partnerid=25811&siteid=5185&Areq=22832BR#jobDetails=860935_5185",
    image_url: "/static/img/hp.png",
  },
       {
    id: 59,
    heading: "Intern | NetApp | Bangalore",
    link: "https://careers.netapp.com/job/bengaluru/intern/27600/64145961392",
    image_url: "/static/img/hp.png",
  },
      {
    id: 58,
    heading: "Trainee | TCS BPS | Multiple Location",
    link: "https://www.tcs.com/careers/india/tcs-bps-fresher-hiring-2024",
    image_url: "/static/img/hp.png",
  },
      {
    id: 57,
    heading: "Graduate Engineer Trainee | NTT DATA | Bangalore",
    link: "https://careers.services.global.ntt/global/en/job/R-110031/apply",
    image_url: "/static/img/hp.png",
  },
      {
    id: 56,
    heading: "Associate | WNS | Bangalore",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999968409093-associate-sr-associate",
    image_url: "/static/img/hp.png",
  },
              {
    id: 55,
    heading: "Software Engineering | Goldman Sachs | Bangalore",
    link: "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/LateralHiring/job/124502",
    image_url: "/static/img/hp.png",
  },
              {
    id: 54,
    heading: "Process Advisor | Barclays | Pune",
    link: "https://search.jobs.barclays/job/pune/process-advisor/13015/63867153760",
    image_url: "/static/img/hp.png",
  },
              {
    id: 53,
    heading: "Trainee | Siemens | Bangalore",
    link: "https://jobs.siemens.com/careers/job?domain=siemens.com&pid=563156119319852&domain=siemens.com",
    image_url: "/static/img/hp.png",
  },
           {
    id: 52,
    heading: "Analyst | HSBC | Bangalore",
    link: "https://mycareer.hsbc.com/en_GB/external/PipelineDetail/Analyst-Data-Governance-GSC-S/216031?src=JB-257546",
    image_url: "/static/img/hp.png",
  },
           {
    id: 51,
    heading: "Web Developer | Lenovo | Bangalore",
    link: "https://jobs.lenovo.com/en_US/careers/JobDetail/Web-Developer/55803#",
    image_url: "/static/img/hp.png",
  },
           {
    id: 50,
    heading: "Tech Internship | Agoda | Gurgaon",
    link: "https://careersatagoda.com/job/5417820-tech-internship-2024-india-based-gurgaon-office/",
    image_url: "/static/img/hp.png",
  },
          {
    id: 49,
    heading: "Business Technology Analyst | Deloitte | Hyderabad",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-EH24-Tax-Business-Technology-Analyst-SAP-FI-SD-Fresher-NSE/176139",
    image_url: "/static/img/hp.png",
  },
          {
    id: 48,
    heading: "Associate | Sutherland | Chennai",
    link: "https://unstop.com/jobs/associate-customer-service-sutherland-global-952364?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
          {
    id: 47,
    heading: "Product Marketers | ZOHO | Chennai",
    link: "https://careers.zohocorp.com/forms/fcc89b5ebd373d598e0224d10f2199d1113aee614efa3264984aa32841436332",
    image_url: "/static/img/hp.png",
  },
        {
    id: 46,
    heading: "Business Analyst | Infosys | Bangalore/Hybrid",
    link: "https://career.infosys.com/jobdesc?jobReferenceCode=INFSYS-NAUKRI-178682&sourceId=4001",
    image_url: "/static/img/hp.png",
  },
        {
    id: 45,
    heading: "Platform Support Associate | Accenture | Hyderabad",
    link: "https://www.accenture.com/in-en/careers/jobdetails?id=AIOC-S01513200_en&title=Platform%20Support%20New%20Associate",
    image_url: "/static/img/hp.png",
  },
        {
    id: 44,
    heading: "Quality Engineer | Service Now| Hyderabad",
    link: "https://unstop.com/jobs/software-quality-engineer-servicenow-946323?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
     {
    id: 43,
    heading: "Engineer 1 | American Express | Bangalore/Hybrid",
    link: "https://aexp.eightfold.ai/careers/job/21092401?domain=aexp.com",
    image_url: "/static/img/hp.png",
  },
     {
    id: 42,
    heading: "Associate Software Developer | Cyntexa | Jaipur",
    link: "https://cyntexa.com/careers/associate-software-developer/",
    image_url: "/static/img/hp.png",
  },
     {
    id: 41,
    heading: "Data Engineer | Pearson | Bangalore",
    link: "https://pearson.jobs/bangalore-ind/data-engineer-intern/A7DBAA9089EF49D79B56F24697A6155A/job/",
    image_url: "/static/img/hp.png",
  },
             {
    id: 40,
    heading: "Support Analyst | Revolut | Work From Home",
    link: "https://www.revolut.com/careers/position/support-specialist-identity-and-verification-analyst-35ee6d79-acf3-4dcc-8544-19d8115f2ed6/",
    image_url: "/static/img/hp.png",
  },
             {
    id: 39,
    heading: "Software Engineer | Cognizant | Bangalore",
    link: "https://careers.cognizant.com/global/en/job/COGNGLOBAL00058595801/Software-Engineer",
    image_url: "/static/img/hp.png",
  },
             {
    id: 38,
    heading: "Technical Support Engineer | IBM | Bangalore",
    link: "https://krb-sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26059&siteid=5016&PageType=JobDetails&jobid=730146#jobDetails=730146_5016",
    image_url: "/static/img/hp.png",
  },
         {
    id: 37,
    heading: "Process Associate | Genpact | Noida",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?src=DS-10971&job=1322997",
    image_url: "/static/img/hp.png",
  },
         {
    id: 36,
    heading: "Financial Analyst | Alight | Work From Home",
    link: "https://careers.alight.com/us/en/job/ALIGUSR28009EXTERNALENUS/Financial-Analyst-I",
    image_url: "/static/img/hp.png",
  },
         {
    id: 35,
    heading: "Software Engineer | Infor | Bangalore",
    link: "https://careers.infor.com/en_US/careers/JobDetail/Software-Engineer-Associate/13323",
    image_url: "/static/img/hp.png",
  },
        {
    id: 34,
    heading: "Data Analyst | Walmart | Bangalore",
    link: "https://walmart.wd5.myworkdayjobs.com/en-US/WalmartExternal/job/DATA-ANALYST-II--DATA-ANALYTICS_R-1796887-1",
    image_url: "/static/img/hp.png",
  },
        {
    id: 33,
    heading: "Program Analyst | WNS | Mumbai",
    link: "https://jobs.smartrecruiters.com/WNSGlobalServices144/743999978597288-ref31776o-end-user-computing-desktop-support-mumbai-wfo-senior-program-analyst-eit",
    image_url: "/static/img/hp.png",
  },
        {
    id: 32,
    heading: "Analyst | Morgan Stanley | Mumbai",
    link: "https://morganstanley.eightfold.ai/careers?pid=549777250362&domain=morganstanley.com&sort_by=relevance",
    image_url: "/static/img/hp.png",
  },
       {
    id: 31,
    heading: "Customer Executive | Groww | Work From Home",
    link: "https://groww.skillate.com/jobs/54143",
    image_url: "/static/img/hp.png",
  },
       {
    id: 30,
    heading: "QA Engineer | Peakflo | Work From Home",
    link: "https://app.dover.io/apply/peakflo/c785fb54-e416-4748-879a-313fdb1e6f7a?rs=42706078",
    image_url: "/static/img/hp.png",
  },
       {
    id: 29,
    heading: "Cloud Specialist | Hyland | Work From Home",
    link: "https://careers-hyland.icims.com/jobs/11504/cloud-specialist-2/job?mode=job&iis=Job%2BBoard&mobile=true&width=390&height=669&bga=true&needsRedirect=false&jan1offset=330&jun1offset=330",
    image_url: "/static/img/hp.png",
  },
     {
    id: 28,
    heading: "Associate Analyst | EY | Work From Home",
    link: "https://unstop.com/jobs/associate-analyst-ey-ernst-young-948846?lb=IqOiHS62&utm_medium=Share&utm_source=shortUrl",
    image_url: "/static/img/hp.png",
  },
     {
    id: 27,
    heading: "SW Test Engineer | Amdocs | Pune",
    link: "https://jobs.amdocs.com/careers/job/563430997179581",
    image_url: "/static/img/hp.png",
  },
     {
    id: 26,
    heading: "Trainee Engineer | NTT Data | Mumbai",
    link: "https://careers.services.global.ntt/global/en/job/NTT1GLOBALR112898EXTERNALENGLOBAL/Trainee-Engineer",
    image_url: "/static/img/hp.png",
  },
     {
    id: 25,
    heading: "Data Analyst | Wipro | Hyderabad",
    link: "https://careers.wipro.com/careers-home/jobs/3066940",
    image_url: "/static/img/hp.png",
  },
     {
    id: 24,
    heading: "Salesforce Developer | Pearson | Bangalore",
    link: "https://pearson.jobs/bangalore-ind/salesforce-developer-intern/FCF1D1167E8A48CBA486F65F3F1C8296/job/?vs=1554",
    image_url: "/static/img/hp.png",
  },
     {
    id: 23,
    heading: "Graduate Engineer Trainee | Invesco | Hyderabad",
    link: "https://invesco.wd1.myworkdayjobs.com/en-US/intelliflo/job/Hyderabad-Telangana/Graduate-Engineer-Trainee_R-5629",
    image_url: "/static/img/hp.png",
  },
     {
    id: 22,
    heading: "CXQO Associate | Amazon | Hyderabad",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/dirc1/apply/?event=14050&job=58038",
    image_url: "/static/img/hp.png",
  },
  {
    id: 21,
    heading: "Domain Trainee | Genpact | Jaipur",
    link: "https://genpact.taleo.net/careersection/sgy_external_career_section/jobdetail.ftl?job=INS023413",
    image_url: "/static/img/hp.png",
  },
  {
    id: 20,
    heading: "QA Engineer | ZOHO Corp | Chennai",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614913581",
    image_url: "/static/img/hp.png",
  },
  {
    id: 19,
    heading: "Consultant Internship | Deloitte | Bangalore",
    link: "https://jobsindia.deloitte.com/job/Bengaluru-Consulting-Internship/23914944/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 18,
    heading: "Software Development Engineer | Urban Company | Gurgaon",
    link: "https://careers.urbancompany.com/jobDetail?id=eb369381-1cfe-432f-affc-12070d83a2c6",
    image_url: "/static/img/hp.png",
  },
  {
    id: 17,
    heading: "Analyst | EY | Noida",
    link: "https://careers.ey.com/ey/job/Noida-Analyst-Forensics-National-ASU-Forensics-Investigations-&-Compliance-Noida-UP-201304/1003553001/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 16,
    heading: "Quality Analyst | Revolut | Work From Home",
    link: "https://www.revolut.com/en-IN/careers/position/quality-assurance-analyst-0f7bfdfb-6fd1-4fbe-b586-f62f84536fa9/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 15,
    heading: "Software Engineer Intern | NIKE | Bangalore",
    link: "https://jobs.nike.com/job/R-24752?cp=76060516106_aff_je6NUbpObpQ&ranMID=41134&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-UmBg0FI_AoHwGdLO5ac13w",
    image_url: "/static/img/hp.png",
  },
  {
    id: 14,
    heading: "iOS Developer | Meesho | Bangalore",
    link: "https://jobs.lever.co/meesho/6e0e5074-e1bb-41c6-89bb-2c20d36d4b0f/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 13,
    heading: "Software Engineer | Microsoft | Bangalore / WFH",
    link: "https://jobs.careers.microsoft.com/global/en/job/1704435/Software-Engineer",
    image_url: "/static/img/hp.png",
  },
  {
    id: 12,
    heading: "Quality Associate | Amazon | Hyderabad",
    link: "https://amazonvirtualhiring.hirepro.in/registration/incta/ju0f4/apply/?j=58218&e=14250",
    image_url: "/static/img/hp.png",
  },
  {
    id: 11,
    heading: "Associate Consultant | KPMG | Bangalore",
    link: "https://ejgk.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/INTG10015744",
    image_url: "/static/img/hp.png",
  },
  {
    id: 10,
    heading: "Associate Software Engineer | Oracle | Bangalore",
    link: "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/233846",
    image_url: "/static/img/hp.png",
  },
  {
    id: 9,
    heading: "Software Development Engineer | Adobe | Noida",
    link: "https://careers.adobe.com/us/en/job/ADOBUSR145089EXTERNALENUS/Software-Development-Engineer",
    image_url: "/static/img/hp.png",
  },
  {
    id: 8,
    heading: "Developer Associate | SAP | Bangalore",
    link: "https://jobs.sap.com/job/Bangalore-Developer-Associate-KA-560066/1055158601/",
    image_url: "/static/img/hp.png",
  },
  {
    id: 7,
    heading: "Software Developer | ZOHO | Pan India",
    link: "https://www.zoho.com/careers/jobdetails/?job_id=2803000614929615",
    image_url: "/static/img/hp.png",
  },
  {
    id: 6,
    heading: "Software Engineer | Myntra | Bangalore",
    link: "https://boards.greenhouse.io/myntra/jobs/7216939002?",
    image_url: "/static/img/hp.png",
  },
  {
    id: 5,
    heading: "Process Analyst | IBM | Bangalore",
    link: "https://www.naukri.com/job-listings-process-analyst-recruitment-ibm-india-pvt-limited-bengaluru-0-to-3-years-260324910641?src=jobsearchDesk&sid=17115543450314158&xp=10&px=1&nignbevent_src=jobsearchDeskGNB",
    image_url: "/static/img/hp.png",
  },
  {
    id: 4,
    heading: "System Analyst | Nielsen | Bangalore",
    link: "https://jobs.lever.co/nielsen/fed9aa65-af08-42b3-b740-441e4da27f02",
    image_url: "/static/img/hp.png",
  },
  {
    id: 3,
    heading: "Development Associate | Accenture | Pan India",
    link: "https://indiacampus.accenture.com/myzone/accenture/1/jobs/25377/job-details",
    image_url: "/static/img/jnj.png",
  },
  {
    id: 2,
    heading: "Technology Analyst | Deloitte | Hyderabad/Pune",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/USI-EH24-TAX-GESTC-B2B-Helpdesk-BTA-Hyd-Pun/140758",
    image_url: "/static/img/infor.png",
  },
  {
    id: 1,
    heading: "Data Analyst | Walmart | Bangalore",
    link: "https://walmart.wd5.myworkdayjobs.com/en-US/WalmartExternal/job/DATA-ANALYST-II--DATA-ANALYTICS_R-1796887-1",
    image_url: "/static/img/Deloitte_Logo.png",
  },
];
